
DELETE http://localhost:3001/api/persons/3

### Test adding a person

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Test McGee",
    "number": "118 188"
}